
import React from 'react';
import { Icon } from './Icon';
import { BrutalistButton } from './BrutalistButton';
import { LazyArtifact } from './LazyArtifact';
import { CaseStudy } from '../types';

interface ArticleViewProps {
  study: CaseStudy;
  onBack: () => void;
  onEdit: (study: CaseStudy) => void;
  onPublish: (study: CaseStudy) => void;
}

export const ArticleView: React.FC<ArticleViewProps> = ({ study, onBack, onEdit, onPublish }) => {
  const downloadFile = (content: string, fileName: string, contentType: string) => {
    const a = document.createElement("a");
    const file = new Blob([content], { type: contentType });
    a.href = URL.createObjectURL(file);
    a.download = fileName;
    a.click();
    URL.revokeObjectURL(a.href);
  };

  const handleDownloadJson = () => {
    const jsonContent = JSON.stringify(study, null, 2);
    downloadFile(jsonContent, `${study.title.toLowerCase().replace(/\s+/g, '-')}.json`, 'application/json');
  };

  const handleDownloadMarkdown = () => {
    const markdown = `# ${study.title}
Date: ${new Date(study.date).toLocaleDateString()}
Status: ${study.status}
Tags: ${study.tags.join(', ')}

## The Challenge
${study.problem}

## Strategy & Execution
${study.approach}

## Outcome
${study.outcome}

## Next Steps
${study.nextSteps}

## Artifacts
${study.artifacts.map(a => `- ${a.aiName} (${a.fileType})`).join('\n')}

---
Generated by DEVSIGNER LOG
`;
    downloadFile(markdown, `${study.title.toLowerCase().replace(/\s+/g, '-')}.md`, 'text/markdown');
  };

  const handleShare = () => {
    if (navigator.share) {
      navigator.share({
        title: study.title,
        text: study.problem,
        url: window.location.href,
      }).catch(console.error);
    } else {
      navigator.clipboard.writeText(window.location.href);
      alert('Link copied to clipboard');
    }
  };

  return (
    <div className="animate-in slide-in-from-right-12 duration-500 bg-white text-black selection:bg-amber-300">
      {/* Sticky Navigation Bar */}
      <div className="sticky top-0 bg-white border-b-4 border-black p-4 z-40 flex justify-between items-center md:px-6">
        <button 
          onClick={onBack} 
          className="flex items-center gap-3 font-black uppercase hover:translate-x-[-4px] transition-transform group"
        >
          <div className="bg-black text-white p-2 group-hover:bg-amber-300 group-hover:text-black transition-colors brutalist-border">
            <Icon name="ArrowLeft" size={18} />
          </div>
          <span className="mono text-xs hidden sm:inline">Feed_Return</span>
        </button>
        <div className="flex gap-3">
          <BrutalistButton 
            variant="secondary" 
            className="px-5 py-2 text-xs brutalist-shadow-sm"
            onClick={() => onEdit(study)}
          >
            <Icon name="Edit3" size={14} />
            Edit_Core
          </BrutalistButton>
          <BrutalistButton 
            className="px-5 py-2 text-xs bg-amber-300 brutalist-shadow-sm"
            onClick={() => onPublish(study)}
            disabled={study.status === 'published'}
          >
            {study.status === 'published' ? 'Published' : 'Publish_Final'}
          </BrutalistButton>
        </div>
      </div>

      <article className="max-w-6xl mx-auto px-4 md:px-12 py-12 pb-48">
        <header className="mb-20 border-b-8 border-black pb-12">
          <div className="flex flex-wrap gap-2 mb-8">
            {study.tags.map(t => (
              <span key={t} className="bg-black text-amber-300 px-3 py-1 text-[10px] font-black uppercase tracking-widest italic">
                #{t}
              </span>
            ))}
          </div>
          
          <h1 className="text-4xl md:text-7xl lg:text-8xl font-black leading-tight tracking-tight uppercase mb-12 italic break-words">
            {study.title}
          </h1>

          <div className="grid grid-cols-2 md:grid-cols-4 gap-0 border-4 border-black bg-black">
            <div className="bg-white p-6 border-r-4 border-black group hover:bg-amber-300 transition-colors">
              <span className="mono text-[10px] uppercase opacity-50 block mb-2 font-black">Timestamp</span>
              <span className="font-bold text-lg">{new Date(study.date).toLocaleDateString()}</span>
            </div>
            <div className="bg-white p-6 border-r-4 border-black group hover:bg-amber-300 transition-colors">
              <span className="mono text-[10px] uppercase opacity-50 block mb-2 font-black">Status</span>
              <span className="font-bold text-lg text-green-600 uppercase italic underline decoration-2">{study.status}</span>
            </div>
            <div className="bg-white p-6 border-r-4 border-black group hover:bg-amber-300 transition-colors">
              <span className="mono text-[10px] uppercase opacity-50 block mb-2 font-black">Evidence</span>
              <span className="font-bold text-lg">{study.artifacts.length} Assets</span>
            </div>
            <div className="bg-white p-6 group hover:bg-amber-300 transition-colors">
              <span className="mono text-[10px] uppercase opacity-50 block mb-2 font-black">Ref_ID</span>
              <span className="font-bold text-lg truncate block">#{study.id.slice(0, 8)}</span>
            </div>
          </div>
        </header>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-16">
          <div className="lg:col-span-8 space-y-24">
            <section className="animate-in fade-in slide-in-from-bottom-8 duration-700">
              <h2 className="text-4xl font-black uppercase mb-8 flex items-baseline gap-4 italic border-l-8 border-amber-300 pl-6">
                <span className="text-black/20 font-mono not-italic text-2xl">01/</span>
                The_Challenge
              </h2>
              <div className="bg-zinc-50 brutalist-border p-8 md:p-12 border-l-[16px] border-l-black relative">
                <Icon name="Quote" size={40} className="absolute -top-6 -right-4 text-black/5" />
                <p className="text-xl md:text-2xl leading-relaxed font-bold text-zinc-900">
                  {study.problem}
                </p>
              </div>
            </section>

            <section className="animate-in fade-in slide-in-from-bottom-8 duration-700 delay-150">
              <h2 className="text-4xl font-black uppercase mb-8 flex items-baseline gap-4 italic border-l-8 border-amber-300 pl-6">
                <span className="text-black/20 font-mono not-italic text-2xl">02/</span>
                Strategy_Execution
              </h2>
              <div className="max-w-prose">
                <p className="text-xl leading-relaxed text-zinc-700">
                  {study.approach}
                </p>
              </div>
            </section>

            <section className="animate-in fade-in slide-in-from-bottom-8 duration-700 delay-300">
              <div className="bg-black text-white p-10 md:p-16 brutalist-shadow-active border-4 border-black relative overflow-hidden">
                <div className="absolute top-0 right-0 w-32 h-32 bg-amber-300 -translate-y-1/2 translate-x-1/2 rotate-45" />
                <h2 className="text-4xl md:text-5xl font-black uppercase mb-8 italic text-amber-300 relative z-10">Outcome</h2>
                <p className="text-lg md:text-2xl leading-relaxed font-bold text-white/90 relative z-10">
                  {study.outcome}
                </p>
              </div>
            </section>

            <section className="animate-in fade-in slide-in-from-bottom-8 duration-700 delay-500">
              <h2 className="text-4xl font-black uppercase mb-8 flex items-baseline gap-4 italic border-l-8 border-amber-300 pl-6">
                <span className="text-black/20 font-mono not-italic text-2xl">04/</span>
                Roadmap_Alpha
              </h2>
              <div className="bg-amber-300/5 brutalist-border p-8 border-dashed">
                <p className="text-xl leading-relaxed text-zinc-600">
                  {study.nextSteps}
                </p>
              </div>
            </section>
          </div>

          <div className="lg:col-span-4 space-y-12">
            <div className="space-y-6">
              <h3 className="text-xl font-black uppercase bg-black text-white px-4 py-2 inline-block italic transform -rotate-1">Evidence_Artifacts</h3>
              <div className="grid grid-cols-1 gap-6">
                {study.artifacts.map((a, idx) => (
                  <div key={a.id} className="brutalist-border bg-white overflow-hidden group hover:bg-zinc-50 transition-all duration-300">
                    <LazyArtifact artifact={a} />
                    <div className="p-4">
                      <p className="mono text-[10px] font-black uppercase leading-tight line-clamp-2 text-zinc-500 group-hover:text-black">{a.aiName}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            <div className="brutalist-border p-8 bg-white space-y-8 sticky top-32 overflow-hidden flex flex-col max-h-[85vh]">
              <div className="flex items-center gap-3 border-b-4 border-black pb-4 mb-2 shrink-0">
                 <div className="bg-black text-amber-300 p-2 brutalist-border">
                  <Icon name="Database" size={20} />
                 </div>
                 <h4 className="font-black text-lg uppercase italic leading-none">Intelligence_Meta</h4>
              </div>
              
              <div className="space-y-8 overflow-y-auto no-scrollbar pr-2 flex-1">
                <div className="space-y-3">
                  <span className="block mono text-[10px] font-black bg-zinc-100 px-2 py-1 uppercase border border-black/10 w-fit">SEO_OPTIMIZED_TITLE</span>
                  <p className="text-sm font-black leading-tight uppercase tracking-tight text-zinc-800 break-words">
                    {study.seoMetadata?.title || study.title}
                  </p>
                </div>

                <div className="space-y-3">
                  <span className="block mono text-[10px] font-black bg-zinc-100 px-2 py-1 uppercase border border-black/10 w-fit">META_DESCRIPTION</span>
                  <p className="text-xs font-bold leading-relaxed text-zinc-600 italic">
                    {study.seoMetadata?.description || 'A detailed breakdown of design execution and technical implementation.'}
                  </p>
                </div>

                <div className="space-y-3">
                  <span className="block mono text-[10px] font-black bg-zinc-100 px-2 py-1 uppercase border border-black/10 w-fit">KNOWLEDGE_GRAPH</span>
                  <div className="flex flex-wrap gap-2">
                    {(study.seoMetadata?.keywords || []).map(k => (
                      <span key={k} className="text-[9px] bg-amber-300 border-2 border-black px-2 py-0.5 font-bold uppercase hover:bg-black hover:text-amber-300 transition-colors cursor-default">
                        {k}
                      </span>
                    ))}
                    {(!study.seoMetadata?.keywords || study.seoMetadata.keywords.length === 0) && (
                      <span className="text-[9px] text-zinc-400 mono italic">NO_KEYWORDS_EXTRACTED</span>
                    )}
                  </div>
                </div>

                <div className="pt-6 border-t border-dotted border-black">
                  <div className="flex justify-between items-center mb-1">
                    <span className="mono text-[9px] font-black opacity-40 uppercase">DATA_INTEGRITY</span>
                    <span className="mono text-[9px] font-black text-green-600 uppercase">VERIFIED</span>
                  </div>
                  <div className="flex justify-between items-center">
                    <span className="mono text-[9px] font-black opacity-40 uppercase">NODE_STATUS</span>
                    <span className="mono text-[9px] font-black text-amber-600 uppercase">LIVE_SYNC</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <footer className="mt-48 pt-24 border-t-8 border-black flex flex-col items-center">
          <div className="text-center mb-16 space-y-2">
            <Icon name="CheckCircle" size={48} className="mx-auto mb-6 text-green-500" />
            <h5 className="text-4xl font-black uppercase italic tracking-tighter">Contribution_Logged</h5>
            <p className="mono text-[10px] opacity-40 uppercase font-black tracking-[0.3em]">End of Verified Intelligence Stream</p>
          </div>
          <div className="flex flex-wrap justify-center gap-8">
            <button className="flex flex-col items-center gap-2 group" onClick={handleShare}>
              <BrutalistButton variant="secondary" className="w-16 h-16 !p-0 group-hover:bg-black group-hover:text-amber-300 transition-colors"><Icon name="Share2" size={28} /></BrutalistButton>
              <span className="mono text-[8px] font-black uppercase opacity-0 group-hover:opacity-100 transition-opacity">Share_Node</span>
            </button>
            <button className="flex flex-col items-center gap-2 group" onClick={handleDownloadMarkdown}>
              <BrutalistButton variant="secondary" className="w-16 h-16 !p-0 group-hover:bg-black group-hover:text-amber-300 transition-colors"><Icon name="FileText" size={28} /></BrutalistButton>
              <span className="mono text-[8px] font-black uppercase opacity-0 group-hover:opacity-100 transition-opacity">Export_Markdown</span>
            </button>
            <button className="flex flex-col items-center gap-2 group" onClick={handleDownloadJson}>
              <BrutalistButton variant="secondary" className="w-16 h-16 !p-0 group-hover:bg-black group-hover:text-amber-300 transition-colors"><Icon name="Download" size={28} /></BrutalistButton>
              <span className="mono text-[8px] font-black uppercase opacity-0 group-hover:opacity-100 transition-opacity">Download_JSON</span>
            </button>
          </div>
        </footer>
      </article>
    </div>
  );
};
